apiVersion: v1beta
kind: Secret
metadata:
  name: kickstart-infra
data:
  env_vars:
    - name: AWS_ACCESS_KEY_ID
      value: "AKIAJE3RODAO3Z3xxxx"
    - name: AWS_SECRET_ACCESS_KEY
      value: "P87yGkNjMTFdYaf1eUhyVhGoYcZxxxxxxxzzzz"
  files:
  - path: /home/semaphore/.ssh/kickstart
    content: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQ0KTUlJRW93SUJBQUtDQVFFQTFsVERmY05ZbkdHUTFjZTxxxxxx
  - path: /home/semaphore/.ssh/kickstart.pub
    content: LS0tLS1CRUdJTiBSU0EgUERmY05ZbkdHUTFjZTA5SjhKWStSSHlQaFp6cHFVUnhIQxxxxxx
